<?php
/**
 * Created by PhpStorm.
 * User: wl
 * Date: 16/11/7
 * Time: 19:14
 */
namespace App\Repositories\Eloquent;

use App\Models\Brand;
use App\Repositories\Eloquent\Repository;
use Illuminate\Support\Facades\File;


class BrandRepository extends  Repository
{
    public function model()
    {
        return Brand::class;
    }

    public function create(array $attributes)
    {
        if (isset($attributes['logo'])) {
            $ret = uploadOne($attributes['logo'], 'brand/', 90, [[200, 200]]);
            $attributes['logo'] = $ret['images'][1];
        }

        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function update($id, array $attributes)
    {
        $brand = $this->find($id);
        if (isset($attributes['logo'])) {
            //更新图片
            $ret = uploadOne($attributes['logo'], 'brand/', 90, [[200, 200]]);
            //删除之前的图片
            File::delete($brand->logo);
            $attributes['logo'] = $ret['images'][1];
        }else {
            $attributes['logo'] = $brand->logo;
        }
        return $brand->update($attributes);
    }

    public function getBrandsForSelect()
    {
//        $brands =  $this->all()->pluck('name', 'id');
        $brands = $this->getAllForSelect('name', 'id');
        return $brands;
    }
}