<?php
/**
 * Created by PhpStorm.
 * User: wl
 * Date: 16/11/7
 * Time: 19:14
 */
namespace App\Repositories\Eloquent;

use App\Models\Goods;
use App\Repositories\Eloquent\Repository;

class GoodsRepository extends  Repository
{
    public function model()
    {
        return Goods::class;
    }

    public function create(array $attributes)
    {
        $ret = uploadOne('logo', 'goods/', 90, [[200, 200]]);
        $attributes['logo'] = $ret['images'][0];
        $attributes['sm_logo'] = $ret['images'][1];
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function allForList()
    {
        $allGoods = $this->with('category')->with('brand');
        return $allGoods;
    }

}